export enum ELEMENT_ACTION_TYPES {
  SET_IS_ORDER_HISTORY_POPUP_OPEN = 'element/SET_IS_ORDER_HISTORY_POPUP_OPEN',
  SET_IS_USER_MENU_OPEN = 'element/SET_IS_USER_MENU_OPEN',
  SET_IS_CART_OPEN = 'element/SET_IS_CART_OPEN',
}
